version: '3.8'

services:
  app1:
    build: ./app1
    ports:
      - "3001:3000"
  app2:
    build: ./app2
    ports:
      - "3002:3000"
  app3:
    build: ./app3
    ports:
      - "3003:3000"
  caddy:
    image: caddy:latest
    ports:
      - "3000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app1
      - app2
      - app3
